name: flutter_web_2048
description: 2048 game made with flutter web framework

version: 1.36.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.0+2
  rxdart: ^0.23.1
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.0.3
  get_it: ^4.0.0-release-candidate
  dartz: ^0.8.9
  connectivity: ^0.4.6+2
  data_connection_checker: ^0.3.4
  swipedetector: ^1.2.0
  piecemeal: any
  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  path_provider: ^1.6.0
  pwa: ^0.2.0
  flutter_signin_button: ^1.0.0
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2+1
  font_awesome_flutter: ^8.5.0
  logging: ^0.11.4
  google_sign_in: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  lint: ^1.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
